# Default evaluation configuration (Standard v1.1)
engines: [lexical, semantic, hybrid]
top_k: 80
rerank_top_n: 5
pre_hit_k: 10
post_hit_k: 5
bootstrap_iters: 1000
bootstrap_alpha: 0.05
seed: 42
hybrid_fusion: rrf
hybrid_rrf_k: 60
hybrid_weight_vector: 0.6
hybrid_weight_lexical: 0.4
hybrid_top_k_vector: 80
hybrid_top_k_lexical: 80
chunks_path: chunks.jsonl
runs_dir: runs
templates_dir: templates
report_path: report.html
