escalation:
  bootstrap_pages: 2
  per_section_bootstrap: 1
  lcs_tau_page: 0.38
  lcs_tau_doc: 0.34
  soft_signal_quorum: 2
  strong_signal_quorum: 1
  force_escalate_if_main_pct_below: 0.60
  use_pp_structure: true
thresholds:
  tau_main: 0.60
  tau_main_page_confident: 0.55
  tau_fail_safe_low: 0.52
  tau_bias_high: 0.65
  tau_heading_h12: 0.75
  tau_heading_h3: 0.60
  caption_h_overlap_min: 0.30
  near_image_lh_multiplier: 1.5
  sidenote_max_width_ratio: 0.50
  sidenote_font_z_max: -0.40
  table_ruling_density: 0.60
  quarantined_aux_conf_min: 0.65
bands:
  margin_x_pct: [0.00, 0.09, 0.91, 1.00]
  header_y_pct: 0.12
  footer_y_pct: 0.12
  header_band_h_pct: 0.12
  footer_band_h_pct: 0.12
  body_band_h_pct: 0.76
repetition:
  min_pages: 3
  max_vertical_jitter_px: 20
caption:
  near_image_lh_multiplier: 1.5
  horiz_overlap_min: 0.30
  extended_merge_max_chars: 220
caption_ring:
  R_in_px: 32
  R_out_px: 120
caption_heuristics:
  max_chars: 180
  allow_trailing_colon: false
activity:
  cue_regex: "^(Activity|Let’s|Discuss|Recall|Think|Try)\\b"
callout:
  min_inset_px: 12
  max_width_ratio_vs_body: 0.85
  min_cues_required: 2
  min_leading_ratio_delta: 0.10
sidenote:
  max_width_ratio: 0.50
  font_z_max: -0.40
header_footer:
  heading_size_jump_min_ratio: 1.20
  heading_short_word_max: 8
  require_running_pattern_for_footer: true
continuation_guard:
  indent_tolerance_px: 6
  continuation_lowercase_start: true
footer_bias:
  ambiguity_delta: 0.10
pagebreak:
  defer_aux_until_paragraph_closed: true
hyphen_repair:
  join_lowercase_after_hyphen: true
  join_no_terminal_punct_with_lowercase: true
section_detection:
  gap_leading_min_ratio: 1.5
  allow_dropcap_or_indent_reset_at_top: true
  bold_leadin_colon_allows_section: true
composite_score:
  delta_borderline: 0.10
implicit_section:
  enable: true
  score_threshold: 0.75
  top_region_pct: 0.25
  min_opening_chars: 160
  whitespace_halo_min_lh: 1.2
  dropcap_detect: true
  first_line_indent_delta_px: 8
  chapter_follow_window_pages: 1
  only_when_no_section: true
stitching:
  split_confidence_threshold: 0.65
  top_lookahead_pct: 0.30
  ttl_pages: {aux: 1, pagebreak: 2}
post_pass:
  enable: true
  order: [stitch_first, peel_captions, shrink_caption_bounds, demote_headers, group_activity, dedup_quarantine]
buffers:
  max_aux_per_anchor_per_type: 2
page_turn:
  nextpage_top_window_pct:
    caption: 0.15
    sidenote: 0.20
    callout: 0.25
source_label:
  strategy: free_aux
  distance_px_max: 120
ocr:
  enable_on_low_yield: true
  enable_on_font_anomaly: true
  dpi: 250
