thresholds:
  tau_main: 0.60
  tau_main_page_confident: 0.55
  tau_fail_safe_low: 0.52
  tau_heading_h12: 0.75
  tau_heading_h3: 0.60
  caption_h_overlap_min: 0.30
  near_image_lh_multiplier: 1.5
  sidenote_max_width_ratio: 0.50
  sidenote_font_z_max: -0.40
  table_ruling_density: 0.60
bands:
  margin_x_pct: [0.00,0.09,0.91,1.00]
  header_y_pct: 0.12
  footer_y_pct: 0.12
implicit_section:
  enable: true
  score_threshold: 0.75
  top_region_pct: 0.25
  min_opening_chars: 160
  whitespace_halo_min_lh: 1.2
  dropcap_detect: true
  first_line_indent_delta_px: 8
  chapter_follow_window_pages: 1
buffering:
  max_aux_per_anchor_per_type: 2
  nextpage_top_window_pct:
    caption: 0.15
    sidenote: 0.20
    callout: 0.25
stitching:
  split_confidence_threshold: 0.65
  ttl_pages: {aux:1, pagebreak:2}
escalation:
  bootstrap_pages: 2
  per_section_bootstrap: 1
  lcs_tau_page: 0.38
  lcs_tau_doc: 0.34
  soft_signal_quorum: 2
  strong_signal_quorum: 1
  force_escalate_if_main_pct_below: 0.60
ocr:
  enable_on_low_yield: true
  enable_on_font_anomaly: true
  dpi: 250
