base_url_env: "VLLM_BASE_URL"
model: "llama-3.2-1b-w8a8"
api_key_env: "VLLM_API_KEY"
temperature: 0.3
max_tokens: 800
max_items: 10
timeout_s: 60
seed: 42
window:
  max_pages: 2
  max_chars: 12000
  max_tokens: 1800
